owner: INL
repo: ivdnt-statusoverzicht
sites:
  - name: ivdnt.org
    url: https://ivdnt.org
  - name: anw.ivdnt.org
    url: https://anw.ivdnt.org
  - name: brievenalsbuit.ivdnt.org
    url: https://brievenalsbuit.ivdnt.org
  - name: brievenalsbuit2.ivdnt.org
    url: https://brievenalsbuit2.ivdnt.org
  - name: chn.ivdnt.org
    url: https://chn.ivdnt.org
  - name: corpusgysseling.ivdnt.org
    url: https://corpusgysseling.ivdnt.org
  - name: corpusmiddelnederlands.ivdnt.org
    url: https://corpusmiddelnederlands.ivdnt.org
  - name: dsdd.ivdnt.org
    url: https://dsdd.ivdnt.org/DSDD
  - name: e-ans.ivdnt.org
    url: https://e-ans.ivdnt.org
  - name: evenementen.ivdnt.org
    url: https://evenementen.ivdnt.org
  - name: etymologiebank.ivdnt.org
    url: https://etymologiebank.ivdnt.org
  - name: ewnd.ivdnt.org
    url: https://ewnd.ivdnt.org
  - name: gtb.ivdnt.org
    url: https://gtb.ivdnt.org
  - name: lexiconfrisicum.ivdnt.org
    url: https://lexiconfrisicum.ivdnt.org
  - name: namescape.nl website
    url: https://blog.namescape.nl
  - name: namescape visualizer
    url: https://visualizer.namescape.nl
  - name: opensonar.ivdnt.org
    url: https://portal.clarin.inl.nl/opensonar_frontend/opensonar
  - name: pybossa.taalradar.ivdnt.org
    url: https://pybossa.taalradar.ivdnt.org
  - name: portal.clarin.ivdnt.org
    url: https://portal.clarin.ivdnt.org
  - name: taalradar.ivdnt.org
    url: https://taalradar.ivdnt.org
  - name: taalportaal.org
    url: https://taalportaal.org
  - name: taalmaterialen.ivdnt.org
    url: https://taalmaterialen.ivdnt.org
  - name: uitleenwoordenbank.ivdnt.org
    url: https://uitleenwoordenbank.ivdnt.org
  - name: vertaalwoordenschat.ivdnt.org
    url: https://vertaalwoordenschat.ivdnt.org
  - name: woordcombinaties.ivdnt.org
    url: https://woordcombinaties.ivdnt.org
status-website:
  cname: status.ivdnt.org
  #baseUrl: /ivdnt-statusoverzicht
  logoUrl: https://raw.githubusercontent.com/INL/ivdnt-statusoverzicht/master/assets/int-logo-2regels.png
  name: Status
  introTitle:
  introMessage:
  navbar:
    - title: live status
      href: /
    - title: github
      href: https://github.com/$OWNER/$REPO
    - title: ivdnt.org
      href: https://ivdnt.org
  footer: (c) ivdnt.org
