owner: INL
repo: ivdnt-statusoverzicht
sites:
  - name: ivdnt.org
    url: https://ivdnt.org
  - name: anw.ivdnt.org
    url: https://anw.ivdnt.org
  - name: brievenalsbuit.ivdnt.org
    url: https://brievenalsbuit.ivdnt.org
  - name: brievenalsbuit2.ivdnt.org
    url: https://brievenalsbuit2.ivdnt.org
  - name: chn.ivdnt.org
    url: https://chn.ivdnt.org
  - name: ciplnet.com
    url: https://ciplnet.com
  - name: clarin-be.ivdnt.org
    url: https://clarin-be.ivdnt.org
  - name: corpusgysseling.ivdnt.org
    url: https://corpusgysseling.ivdnt.org
  - name: corpusjuridischnederlands.ivdnt.org
    url: https://corpusjuridischnederlands.ivdnt.org
  - name: corpusmiddelnederlands.ivdnt.org
    url: https://corpusmiddelnederlands.ivdnt.org
  - name: corpusoudfries.ivdnt.org
    url: https://corpusoudfries.ivdnt.org
  - name: corpusoudnederlands.ivdnt.org
    url: https://corpusoudnederlands.ivdnt.org
  - name: couranten.ivdnt.org
    url: https://couranten.ivdnt.org
  - name: dative.ca
    url: https://dative.ca
  - name: dagenta.ivdnt.org
    url: https://dagenta.ivdnt.org
  - name: diamant.ivdnt.org
    url: https://diamant.ivdnt.org
  - name: dsdd.ivdnt.org
    url: https://dsdd.ivdnt.org/DSDD
  - name: e-ans.ivdnt.org
    url: https://e-ans.ivdnt.org
  - name: etymologiebank.ivdnt.org
    url: https://etymologiebank.ivdnt.org
  - name: ewnd.ivdnt.org
    url: https://ewnd.ivdnt.org
  - name: fineco.ivdnt.org
    url: https://fineco.ivdnt.org
  - name: gekaaptebrieven.ivdnt.org
    url: https://gekaaptebrieven.ivdnt.org
  - name: glad.ivdnt.org
    url: https://glad.ivdnt.org
  - name: gretel4.ivdnt.org
    url: https://gretel4.ivdnt.org
  - name: gtb.ivdnt.org
    url: https://gtb.ivdnt.org
  - name: hcd.ivdnt.org
    url: https://hcd.ivdnt.org
  - name: jiddischwoordenboek.nl
    url: https://jiddischwoordenboek.nl
  - name: jwsii.ivdnt.org
    url: https://jwsii.ivdnt.org
  - name: kdutch.ivdnt.org
    url: https://kdutch.ivdnt.org
  - name: kennisbank-begrijpelijketaal.nl
    url: https://kennisbank-begrijpelijketaal.nl
  - name: lexiconfrisicum.ivdnt.org
    url: https://lexiconfrisicum.ivdnt.org
  - name: limburgsluisteren.ivdnt.org
    url: https://limburgsluisteren.ivdnt.org
  - name: mateo.ivdnt.org
    url: https://mateo.ivdnt.org
  - name: neerlandistiek.nl
    url: https://neerlandistiek.nl
  - name: nederlandsedialecten.org
    url: https://nederlandsedialecten.org
  - name: neologismen.ivdnt.org
    url: https://neologismen.ivdnt.org
  - name: opensonar.ivdnt.org
    url: https://portal.clarin.inl.nl/opensonar_frontend/opensonar
  - name: overtaal.be
    url: https://overtaal.be
  - name: pallas.ivdnt.org
    url: https://pallas.ivdnt.org
  - name: picto.ivdnt.org
    url: https://picto.ivdnt.org
  - name: pinkhof.ivdnt.org
    url: https://pinkhof.ivdnt.org
  - name: portal.clarin.ivdnt.org
    url: https://portal.clarin.ivdnt.org
  - name: schatkamer.ivdnt.org
    url: https://schatkamer.ivdnt.org
  - name: scheikunde.ivdnt.org
    url: https://scheikunde.ivdnt.org
  - name: sofeer.ivdnt.org
    url: https://sofeer.ivdnt.org
  - name: taaladvies.net
    url: https://taaladvies.net
  - name: taalmaterialen.ivdnt.org
    url: https://taalmaterialen.ivdnt.org
  - name: transcriptor.nl
    url: https://transcriptor.nl
  - name: uitleenwoordenbank.ivdnt.org
    url: https://uitleenwoordenbank.ivdnt.org
  - name: vertaalwoordenschat.ivdnt.org
    url: https://vertaalwoordenschat.ivdnt.org
  - name: woordcombinaties.ivdnt.org
    url: https://woordcombinaties.ivdnt.org
  - name: woordenlijst.org
    url: https://woordenlijst.org    
  - name: woordpeiler.ivdnt.org
    url: https://woordpeiler.ivdnt.org
status-website:
  cname: status.ivdnt.org
  logoUrl: https://raw.githubusercontent.com/INL/ivdnt-statusoverzicht/master/assets/ivdNt-logo-w-2regels-cmyk.png
  name: Status
  introTitle:
  introMessage: Live status overview of our websites and applications.
  navbar:
    - title: live status
      href: /
    - title: github
      href: https://github.com/$OWNER/$REPO
    - title: ivdnt.org
      href: https://ivdnt.org
i18n:
  footer: ivdnt.org - opensource project by [Upptime](https://upptime.js.org)
